apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: ISG-Genius-dev
  region: us-east-1

managedNodeGroups:
  - name: ISG-Genius-dev
    instanceTypes:
      - m5.large
      - t3.small
      - t3.medium
      - c5.large
    desiredCapacity: 2
    spot: true